#include <iostream>
#include "..\vector.h"
int main() {
    // vector u(2);
    // std::cout << "u: ";
    // u.input();
    // std::cout << "u: ";
    // u.show();
    // std::cout << u[0] << std::endl;
    // u[0] = 5;
    // std::cout << u[0] << std::endl;
    // std::cout << u(1) << std::endl;
    // u(1) = 5;
    // std::cout << u(1) << std::endl;
    // std::cout << "u: ";
    // u.show();
    // vector v(2);
    // std::cout << "v: ";
    // v.input();
    // std::cout << "v: ";
    // v.show();
    // std::cout << "(++u) + v: ";
    // ((++u) + v).show();
    // std::cout << "u: ";
    // u.show();
    // std::cout << "v: ";
    // v.show();
    // std::cout << "(u++) + v: ";
    // ((u++) + v).show();
    // std::cout << "u: ";
    // u.show();
    // std::cout << "v: ";
    // v.show();
    // std::cout << "(--u) - v: ";
    // ((--u) - v).show();
    // std::cout << "u: ";
    // u.show();
    // std::cout << "v: ";
    // v.show();
    // std::cout << "(u--) - v: ";
    // ((u--) - v).show();
    // std::cout << "u: ";
    // u.show();
    // std::cout << "v: ";
    // v.show();
    // if(u == v) std::cout << "u = v" << std::endl;
    // if(u != v) std::cout << "u != v" << std::endl;
    // std::cout << "Do dai cua u: " << !u;
    // vector u(2);
    // std::cout << "u: ";
    // u.input();
    // std::cout << "u: ";
    // u.show();
    // vector v;
    // v=u;
    // std::cout << "v: ";
    // v.show();
    vector u;
    vector v;
    std::cin >> u >> v;
    std::cout << u << v;
    return 0;
}
